//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilterDataGrid.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilterDataGrid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加条件 的本地化字符串。
        /// </summary>
        public static string AddCondition {
            get {
                return ResourceManager.GetString("AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对齐方式 的本地化字符串。
        /// </summary>
        public static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (全选) 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与 的本地化字符串。
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用筛选 的本地化字符串。
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序排序 的本地化字符串。
        /// </summary>
        public static string AscSort {
            get {
                return ResourceManager.GetString("AscSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消分组 的本地化字符串。
        /// </summary>
        public static string CancelGroup {
            get {
                return ResourceManager.GetString("CancelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        public static string CenterAlign {
            get {
                return ResourceManager.GetString("CenterAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有筛选 的本地化字符串。
        /// </summary>
        public static string ClearAllFilter {
            get {
                return ResourceManager.GetString("ClearAllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有排序 的本地化字符串。
        /// </summary>
        public static string ClearAllSort {
            get {
                return ResourceManager.GetString("ClearAllSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空条件 的本地化字符串。
        /// </summary>
        public static string ClearCondition {
            get {
                return ResourceManager.GetString("ClearCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除当前筛选 的本地化字符串。
        /// </summary>
        public static string ClearCurrentFilter {
            get {
                return ResourceManager.GetString("ClearCurrentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除过滤器 的本地化字符串。
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除排序 的本地化字符串。
        /// </summary>
        public static string ClearSort {
            get {
                return ResourceManager.GetString("ClearSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭搜索面板 的本地化字符串。
        /// </summary>
        public static string CloseSearchPanel {
            get {
                return ResourceManager.GetString("CloseSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部收合 的本地化字符串。
        /// </summary>
        public static string CollapsedAllGroup {
            get {
                return ResourceManager.GetString("CollapsedAllGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名选择 的本地化字符串。
        /// </summary>
        public static string ColumnSelect {
            get {
                return ResourceManager.GetString("ColumnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列宽调整 的本地化字符串。
        /// </summary>
        public static string ColumnWidthAdjust {
            get {
                return ResourceManager.GetString("ColumnWidthAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        public static string Contain {
            get {
                return ResourceManager.GetString("Contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索(包含) 的本地化字符串。
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数： 的本地化字符串。
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义筛选 的本地化字符串。
        /// </summary>
        public static string CustomFilter {
            get {
                return ResourceManager.GetString("CustomFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请完善过滤条件！ 的本地化字符串。
        /// </summary>
        public static string CustomizeFilterTip {
            get {
                return ResourceManager.GetString("CustomizeFilterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除条件 的本地化字符串。
        /// </summary>
        public static string DeleteCondition {
            get {
                return ResourceManager.GetString("DeleteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序排序 的本地化字符串。
        /// </summary>
        public static string DescSort {
            get {
                return ResourceManager.GetString("DescSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        public static string EndPage {
            get {
                return ResourceManager.GetString("EndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾 的本地化字符串。
        /// </summary>
        public static string EndWith {
            get {
                return ResourceManager.GetString("EndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等于 的本地化字符串。
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部展开 的本地化字符串。
        /// </summary>
        public static string ExpandedAllGroup {
            get {
                return ResourceManager.GetString("ExpandedAllGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次共导出数据【{0}】条。 的本地化字符串。
        /// </summary>
        public static string ExportTip {
            get {
                return ResourceManager.GetString("ExportTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转 的本地化字符串。
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于 的本地化字符串。
        /// </summary>
        public static string Greater {
            get {
                return ResourceManager.GetString("Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大于等于 的本地化字符串。
        /// </summary>
        public static string GreaterEqual {
            get {
                return ResourceManager.GetString("GreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此列分组 的本地化字符串。
        /// </summary>
        public static string GroupColumn {
            get {
                return ResourceManager.GetString("GroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组行高 的本地化字符串。
        /// </summary>
        public static string GroupHeightAdjust {
            get {
                return ResourceManager.GetString("GroupHeightAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面设置 的本地化字符串。
        /// </summary>
        public static string InterfaceSettings {
            get {
                return ResourceManager.GetString("InterfaceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隔行换色 的本地化字符串。
        /// </summary>
        public static string InterlacedColor {
            get {
                return ResourceManager.GetString("InterlacedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string IsFalse {
            get {
                return ResourceManager.GetString("IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string IsTrue {
            get {
                return ResourceManager.GetString("IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页显示的数量 的本地化字符串。
        /// </summary>
        public static string ItemsInPage {
            get {
                return ResourceManager.GetString("ItemsInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件名 的本地化字符串。
        /// </summary>
        public static string LayoutName {
            get {
                return ResourceManager.GetString("LayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居左 的本地化字符串。
        /// </summary>
        public static string LeftAlign {
            get {
                return ResourceManager.GetString("LeftAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于 的本地化字符串。
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等于 的本地化字符串。
        /// </summary>
        public static string LessEqual {
            get {
                return ResourceManager.GetString("LessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为空 的本地化字符串。
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或 的本地化字符串。
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它设置 的本地化字符串。
        /// </summary>
        public static string OtherSetting {
            get {
                return ResourceManager.GetString("OtherSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置完成！ 的本地化字符串。
        /// </summary>
        public static string ResetCompleted {
            get {
                return ResourceManager.GetString("ResetCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置布局 的本地化字符串。
        /// </summary>
        public static string ResetLayout {
            get {
                return ResourceManager.GetString("ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居右 的本地化字符串。
        /// </summary>
        public static string RightAlign {
            get {
                return ResourceManager.GetString("RightAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行头调整 的本地化字符串。
        /// </summary>
        public static string RowHeaderWidthAdjust {
            get {
                return ResourceManager.GetString("RowHeaderWidthAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行高调整 的本地化字符串。
        /// </summary>
        public static string RowHeightAdjust {
            get {
                return ResourceManager.GetString("RowHeightAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存完成！ 的本地化字符串。
        /// </summary>
        public static string SaveCompleted {
            get {
                return ResourceManager.GetString("SaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存布局 的本地化字符串。
        /// </summary>
        public static string SaveLayout {
            get {
                return ResourceManager.GetString("SaveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索面板 的本地化字符串。
        /// </summary>
        public static string SearchPanel {
            get {
                return ResourceManager.GetString("SearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入需要搜索的关键字 的本地化字符串。
        /// </summary>
        public static string SearchWord {
            get {
                return ResourceManager.GetString("SearchWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部居中显示 的本地化字符串。
        /// </summary>
        public static string ShowCenter {
            get {
                return ResourceManager.GetString("ShowCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认显示全局搜索 的本地化字符串。
        /// </summary>
        public static string ShowGlobalSearch {
            get {
                return ResourceManager.GetString("ShowGlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏列 的本地化字符串。
        /// </summary>
        public static string ShowHideColumn {
            get {
                return ResourceManager.GetString("ShowHideColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示垂直网格线 的本地化字符串。
        /// </summary>
        public static string ShowVerticalGridLine {
            get {
                return ResourceManager.GetString("ShowVerticalGridLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头 的本地化字符串。
        /// </summary>
        public static string StartWith {
            get {
                return ResourceManager.GetString("StartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 求和： 的本地化字符串。
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题栏调整 的本地化字符串。
        /// </summary>
        public static string TitleBarAdjust {
            get {
                return ResourceManager.GetString("TitleBarAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含 的本地化字符串。
        /// </summary>
        public static string UnContain {
            get {
                return ResourceManager.GetString("UnContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等于 的本地化字符串。
        /// </summary>
        public static string UnEqual {
            get {
                return ResourceManager.GetString("UnEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不为空 的本地化字符串。
        /// </summary>
        public static string UnNull {
            get {
                return ResourceManager.GetString("UnNull", resourceCulture);
            }
        }
    }
}
